### ISSUE TITLE
XLM, DOGE amount entry not possible

### ISSUE THREAD

**Issue by yusakapon** [yusakapon/dydx-chrome-extension#101]
* XLM, DOGE数量入力できない

**Comment by yusakapon** [comment]
@yusakuvol   
* amountがNANになるっぽくて入力がおかしい
* `The specified value "NaN" cannot be parsed, or is out of range.`のワーニングが出ている  

原因わかるかな？

**Comment by yusakuvol** [comment]
明示的にキャストしてあげてら直る
roundByStepSize(Number(amount.value) + Number(step.value))

**Comment by yusakuvol** [comment]
ただ、別問題だけど、少数計算の誤差が根本的に治っていない

**Comment by yusakapon** [comment]
なるほど。  
他の通貨で発生しないのはなんでかな

**Comment by yusakapon** [comment]
.toFixedしてnumberにキャストすればいけるかな？

**Comment by yusakuvol** [comment]
> 誤差はtoFixedしてnumberにキャストすればいけるかな？
numberにキャストしてtoFixedしたらいけそう

**Comment by yusakuvol** [comment]
いや、toFixedいらんかも。
あとでMath.roundしてるから

**Comment by yusakuvol** [comment]
### 整理
- ワーニングの原因２つありました。
1. 文字列で計算されている場合がある
2. stepSizeが100以上の時、roundNumが0になってしまい、後続で計算できない
 (1 / 100を四捨五入して0になっている)
```
const roundByStepSize = (num: number) => {
  const roundNum = Math.round(1 / stepSize.value);
  return Math.round(num * roundNum) / roundNum;
};
```

**Comment by yusakuvol** [comment]
#103
