### ISSUE TITLE
Display message in case of order error

### ISSUE THREAD

**Issue by yusakapon** [yusakapon/dydx-chrome-extension#35]
* 注文エラー時はメッセージを表示する

**Comment by yusakuvol** [comment]
一旦alertでメッセージ出してみた。
イメージは拡張機能のどこかに表示？ポップアップ表示？

<img width="1054" alt="スクリーンショット 2022-05-01 10 40 38" src="https://user-images.githubusercontent.com/65386908/166128539-43ca0e43-9441-430a-a93d-5a1e9e8ac4be.png">

**Comment by yusakapon** [comment]
導線的には拡張機能のどこかに表示かなー  
タイトルとアドレスの間か、アドレスの下とか  
×で表示消せるようにしてほしい

**Comment by yusakuvol** [comment]
一旦本家のメッセージっぽく作ってみた

<img width="394" alt="スクリーンショット 2022-05-05 15 28 53" src="https://user-images.githubusercontent.com/65386908/166872596-2d833a1e-7d06-4214-826e-1a56c0718cc5.png">
<img width="384" alt="スクリーンショット 2022-05-05 15 28 32" src="https://user-images.githubusercontent.com/65386908/166872598-69d41dfa-f45b-48ef-98bb-041ed2daac15.png">

**Comment by yusakapon** [comment]
> 一旦本家のメッセージっぽく作ってみた
> 
> <img alt="スクリーンショット 2022-05-05 15 28 53" width="394" src="https://user-images.githubusercontent.com/65386908/166872596-2d833a1e-7d06-4214-826e-1a56c0718cc5.png">
> 
> <img alt="スクリーンショット 2022-05-05 15 28 32" width="384" src="https://user-images.githubusercontent.com/65386908/166872598-69d41dfa-f45b-48ef-98bb-041ed2daac15.png">

いい感じ！
