### ISSUE TITLE
CI research and implementation

### ISSUE THREAD

**Issue by yusakapon** [yusakapon/dydx-chrome-extension#4]
# 実施内容
- CIツールの選定
- 導入

**Comment by tatsukoni-pra** [comment]
# 料金
## CircleCI

- [[Freeプラン](https://circleci.com/ja/pricing/)[](https://www.ariseanalytics.com/activities/report/20201225/)](https://circleci.com/ja/pricing/)なら無料
- ビルド時間: 最大 6,000 分/月

## Github Actions

- パブリックリポジトリであれば完全無料
- [https://www.ariseanalytics.com/activities/report/20201225/](https://www.ariseanalytics.com/activities/report/20201225/)

**Comment by tatsukoni-pra** [comment]
## GithubActions 動作の検証

PHPUnitを実行してみた。
動き的には問題なさそう。
https://github.com/tatsukoni-pra/github-actions-search-v1

**Comment by tatsukoni-pra** [comment]
ツールはpublicレポジトリならば完全無料で使える、GithubActionsでいこうと思います。
動作的にも、CIに関しては問題なさそう。

**Comment by tatsukoni-pra** [comment]
プルリク
https://github.com/yusakapon/dydx-chrome-extension/pull/10
