### ISSUE TITLE
Adjusting the display of Currency <-> USD

### ISSUE THREAD

**Issue by yusakapon** [yusakapon/dydx-chrome-extension#75]
<img width="298" alt="スクリーンショット 2022-04-30 11 27 59" src="https://user-images.githubusercontent.com/57611745/166087003-359ff154-af7e-4ad3-b3d3-99789f372fb1.png">
<img width="288" alt="スクリーンショット 2022-04-30 11 31 03" src="https://user-images.githubusercontent.com/57611745/166087044-a9d36a99-0049-4ebb-b671-bb4df1a142cb.png">

* 本家と同様に単位は入力欄に入れたい
* 通貨とUSD表示はニアリーイコールで繋ぎたい
* 別の項目みたいに見えるので背景色はつなげたい

**Comment by yusakuvol** [comment]
入力欄はやってみた
<img width="366" alt="スクリーンショット 2022-05-05 18 18 26" src="https://user-images.githubusercontent.com/65386908/166895203-d1aebea0-b172-465a-90ad-2b7fd2f61668.png">

**Comment by yusakuvol** [comment]
ニアリーイコールはinputとinputの間？

**Comment by yusakapon** [comment]
> 

そのイメージ！

**Comment by yusakapon** [comment]
> ニアリーイコールはinputとinputの間？

そのイメージ！

**Comment by yusakuvol** [comment]
こんな感じでいい？

<img width="375" alt="スクリーンショット 2022-05-09 21 49 38" src="https://user-images.githubusercontent.com/65386908/167413508-2cc5b07d-ac95-40ab-a25c-668d870a4bbb.png">

**Comment by yusakapon** [comment]
OK!   
数量入力欄の入力できる桁数だけ気になる

**Comment by yusakuvol** [comment]
padding最小+text-smで、8桁くらいまでいける
もっとほしい？

<img width="369" alt="スクリーンショット 2022-05-09 22 22 42" src="https://user-images.githubusercontent.com/65386908/167419444-1d164ea9-a234-4e9b-8160-09d245330731.png">
<img width="369" alt="スクリーンショット 2022-05-09 22 21 28" src="https://user-images.githubusercontent.com/65386908/167419129-0708a149-3fd5-456a-9716-801ac6529912.png">

**Comment by yusakapon** [comment]
それなら大丈夫そう！
