### ISSUE TITLE
Fix a bug in self input

### ISSUE THREAD

**Issue by yusakapon** [yusakapon/dydx-chrome-extension#76]
<img width="298" alt="スクリーンショット 2022-04-30 11 39 31" src="https://user-images.githubusercontent.com/57611745/166087407-0972acbf-1de2-404e-82be-a9cabe10f2ad.png">

* stepは何？
* なぜかstepがpriceに使われている

**Comment by yusakuvol** [comment]
<img width="365" alt="スクリーンショット 2022-05-01 8 53 44" src="https://user-images.githubusercontent.com/65386908/166126416-319e3da4-d6b7-434d-af2d-9311a3b20518.png">

- 右側の数値の+-でstepの数値を設定
- stepは左側のinputを増減させる時の単位
- `(例：step:10のとき、inputの上ボタンをおすとinputが10増加する)`

**Comment by yusakuvol** [comment]
@yusakapon のイメージがあれば修正する

**Comment by yusakapon** [comment]
> <img alt="スクリーンショット 2022-05-01 8 53 44" width="365" src="https://user-images.githubusercontent.com/65386908/166126416-319e3da4-d6b7-434d-af2d-9311a3b20518.png">
> 
> * 右側の数値の+-でstepの数値を設定
> * stepは左側のinputを増減させる時の単位
> * `(例：step:10のとき、inputの上ボタンをおすとinputが10増加する)`

あーそういうことか！一旦これでいいかな！

**Comment by yusakapon** [comment]
注文のpriceがおかしいからそれだけ治してほしい！
