### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'market')

### ISSUE THREAD

**Issue by yusakapon** [yusakapon/dydx-chrome-extension#79]
* `TypeError: Cannot read properties of undefined (reading 'market')`のエラーが出る時がある

**Comment by yusakapon** [comment]
これ自分がいれたコードが原因かも

**Comment by yusakapon** [comment]
再現しなくなった...

**Comment by yusakapon** [comment]
LONGがダメっぽい

**Comment by yusakuvol** [comment]
ごめん、普通にコードミスってた

**Comment by yusakapon** [comment]
https://github.com/yusakapon/dydx-chrome-extension/pull/89
